### ISSUE TITLE
New Feature Label

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/style#11]
## Is your feature request related to a problem? Please describe

We currently don't have a way of labelling/highlighting/warning when a feature is new.
This is good to:
a) show new features off
b) warn when new features might be experimental

## Describe the solution you'd like

One or two ways to highlight a button, maybe a small ribbon or something, that has an icon or word, e.g. "new" or a beta symbol?, and a tooltip that explains the feature is new.

## Describe alternatives you've considered

None

## Additional context

Originally suggest by @BoguslawObara so please let him know when implemented so he can see :-)

**Comment by joshuajames-smith** [comment]
Relates https://github.com/gliff-ai/style/pull/84

**Comment by ChrisBaidoo** [comment]
> Relates #84

@joshuajames-smith  I think I will close this one too because it is covered else where. Thoughts?
