### ISSUE TITLE
MUI-Grid should be a peer dependency

### ISSUE THREAD

**Issue by cooper667** [gliff-ai/style#216]
Bundling it means we ALSO bundle all of material I think, which creates a massive bundle and will create conflicts later

**Comment by cooper667** [comment]
Done @ChrisBaidoo ?

**Comment by ChrisBaidoo** [comment]
I believe you mean, mui-data-grid? If so then it is done. 
<img width="807" alt="Screenshot 2022-06-13 at 09 24 18" src="https://user-images.githubusercontent.com/37402968/173311614-effd08e3-ae61-436c-a294-de65087e55bd.png">
@cooper667
